spring.application.name=GameHubArena
spring.datasource.url=jdbc:postgresql://localhost:5432/gamehub_arena
spring.datasource.username=postgres
spring.datasource.password=Armadietto.01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=q8V7p9sJ1Yt4k3H2m5B8c7L0x9Q2w4E6f1D3h7K8s0U=
jwt.expiration=86400000

rawg.api.key = 709be523349e478da3ca8e56097e1a61
rawg.api.url = https://api.rawg.io/api

