spring.application.name=GameHubArena
spring.datasource.url=jdbc:postgresql://localhost:5432/gamehub_arena
spring.datasource.username=postgres
spring.datasource.password=Armadietto.01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true