spring.application.name=GameHubArena
# TIPS: Configurazione del Database Postgres (requisito fondamentale).
# Queste property dicono a Spring Data JPA dove trovare il DB e come autenticarsi.
spring.datasource.url=jdbc:postgresql://ep-cold-lake-aqxpyjj4.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nGLV5xqeh0RK


# TIPS: ddl-auto=update fa sì che Hibernate aggiorni lo schema del DB (es. creando nuove tabelle) automaticamente all'avvio.
# show-sql=true è molto utile per il debug, permette di vedere le query SQL reali generate dai Proxy/DAO.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=q8V7p9sJ1Yt4k3H2m5B8c7L0x9Q2w4E6f1D3h7K8s0U=
jwt.expiration=86400000

rawg.api.key = 6c03b9338f3949879e5199700c1fed38
rawg.api.url = https://api.rawg.io/api

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
